> quotebase
  known_guilds
    guildid [TINYINT]
    lastconnected [DATETIME]
  name_translation_table
    guildid [TINYINT] [PRIMARY]
    guildname [SMALLTEXT]
  
  <guild id>
    <<Quote Tables Here WIP>>

Tables:
